# Generated by Django 4.0.5 on 2022-06-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parroquia',
            old_name='tipo_Parroquia',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='barrio',
            name='num_edificios',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='num_parques',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='num_viviendas',
            field=models.IntegerField(max_length=100),
        ),
    ]
